apply plugin: 'com.android.application'

android {
    compileSdkVersion 30
    defaultConfig {
        applicationId 'de.yahya.ai'
        minSdkVersion 26
        targetSdkVersion 30
        versionCode 20
        versionName '1.0-celin-foundation'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'com.github.k2-fsa:sherpa-onnx:1.13.4'
}
